#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Date-Holidays
version:      0.02
version_from: lib/Date/Holidays.pm
installdirs:  site
requires:
    Carp:                          0
    Test::Pod::Coverage:           0.08
    Test::More:                    0
    Locale::Country:               0
    File::Spec:                    0
    Test::Pod:                     0.95
    DateTime:                      0
    Exporter:                      0
    UNIVERSAL:                     0
    File::Find:                    0
    Date::Holidays::DK:            0.02

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
