---
name: Date-Holidays
version: 0.14
author:
  - 'Jonas B. Nielsen, (jonasbn) jonasbn@cpan.org'
abstract: a Date::Holidays::* OOP Adapter aggregator
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  DateTime: 0
  Error: 0
  Locale::Country: 0
  Module::Load: 0
  UNIVERSAL: 0
build_requires:
  Test::More: 0
provides:
  Date::Holidays:
    file: lib/Date/Holidays.pm
    version: 0.14
  Date::Holidays::Adapter:
    file: lib/Date/Holidays/Adapter.pm
    version: 0.02
  Date::Holidays::Adapter::AU:
    file: lib/Date/Holidays/Adapter/AU.pm
    version: 0.01
  Date::Holidays::Adapter::DE:
    file: lib/Date/Holidays/Adapter/DE.pm
    version: 0.01
  Date::Holidays::Adapter::DK:
    file: lib/Date/Holidays/Adapter/DK.pm
    version: 0.01
  Date::Holidays::Adapter::ES:
    file: lib/Date/Holidays/Adapter/ES.pm
    version: 0.01
  Date::Holidays::Adapter::FR:
    file: lib/Date/Holidays/Adapter/FR.pm
    version: 0.01
  Date::Holidays::Adapter::GB:
    file: lib/Date/Holidays/Adapter/GB.pm
    version: 0.01
  Date::Holidays::Adapter::JP:
    file: lib/Date/Holidays/Adapter/JP.pm
    version: 0.01
  Date::Holidays::Adapter::NO:
    file: lib/Date/Holidays/Adapter/NO.pm
    version: 0.01
  Date::Holidays::Adapter::PT:
    file: lib/Date/Holidays/Adapter/PT.pm
    version: 0.01
  Date::Holidays::Exception::AdapterInitialization:
    file: lib/Date/Holidays/Exception/AdapterInitialization.pm
    version: 0.01
  Date::Holidays::Exception::AdapterLoad:
    file: lib/Date/Holidays/Exception/AdapterLoad.pm
    version: 0.01
  Date::Holidays::Exception::InvalidCountryCode:
    file: lib/Date/Holidays/Exception/InvalidCountryCode.pm
    version: 0.01
  Date::Holidays::Exception::NoCountrySpecified:
    file: lib/Date/Holidays/Exception/NoCountrySpecified.pm
    version: 0.01
  Date::Holidays::Exception::SuperAdapterLoad:
    file: lib/Date/Holidays/Exception/SuperAdapterLoad.pm
    version: 0.01
  Date::Holidays::Exception::UnsupportedMethod:
    file: lib/Date/Holidays/Exception/UnsupportedMethod.pm
    version: 0.01
no_index:
  directory:
    - t
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
