---
name: Date-Holidays
version: !!perl/hash:Module::Build::Version
  original: 0.08
  version:
    - 0
    - 80
author:
  - 'Jonas B. Nielsen, (jonasbn) jonasbn@cpan.org'
abstract: a Date::Holidays::* OOP wrapper
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  DateTime: 0
  Locale::Country: 0
  UNIVERSAL: 0
build_requires:
  Date::Holidays::DK: 0.02
  File::Find: 0
  File::Spec: 0
  Test::More: 0
provides:
  Date::Holidays:
    file: lib/Date/Holidays.pm
    version: 0.08
generated_by: Module::Build version 0.2804
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
